### ISSUE TITLE
package submited to hackage & maybe one day on nixos

### ISSUE THREAD

**Issue by jpierre03** [expipiplus1/update-nix-fetchgit#11]
I've submited current version on hackage  : https://hackage.haskell.org/package/update-nix-fetchgit .

Tanks to commercialhaskell's process,  hash and attributes used in NixOS (nixpkgs) are available https://github.com/commercialhaskell/all-cabal-metadata/commit/b6fc76b88b954094c0bbda0c29856a6b6df9eb09 

Thoses changes may help to provide `update-nix-fetchgit` into NixOS.

Please let me know hackage users to add as maintainers.

**Comment by expipiplus1** [comment]
Noted. I'm not entirely sure I consider this ready for Hackage at the moment. Perhaps this can act as an incentive to neaten things up a little!

My Hackage username is `jophish`.

**Comment by DavidEGrayson** [comment]
Yeah, this project requires a special version of hnix that cannot be compiled with the latest GHC the last time I checked.

**Comment by jpierre03** [comment]
@DavidEGrayson it (almost works ) compile on nixos-unstable and is integrated : haskellPackages.update-nix-fetchgit (https://github.com/NixOS/nixpkgs/commit/18df98fe9806796ae3eba05a8cf6cd1166223137#diff-e4ed6fefa9564bfd27ee249e42e145e2R182765)
Thanks to @peti process.

@expipiplus1 username added. Hackage accepts experimental packages ... and is a way to increase project visibility. Usually a 0.1.0.0 version is considered pre-alpha.

**Comment by dtzWill** [comment]
Can the hackage version be bumped to include the fix for https://github.com/expipiplus1/update-nix-fetchgit/issues/13 ?

Without it, `haskellPackages.update-nix-fetchgit` no longer builds on NixOS unstable or 17.09 :(.

(I think it works on 17.03, don't know as I'm still compiling dependencies...)

**Comment by sorki** [comment]
I've uploaded `0.1.1.0` to Hackage and will unbreak it in NixOS so it should be available in `nixpkgs` master next week.

**Comment by expipiplus1** [comment]
Thanks!

**Comment by expipiplus1** [comment]
0.1.1 is in nixpkgs master! (and builds)
