### ISSUE TITLE
Cabal package bounds prevent compilation on NixOS unstable

### ISSUE THREAD

**Issue by alistairbill** [expipiplus1/update-nix-fetchgit#13]
```
(...)
Configuring update-nix-fetchgit-0.1.0.0...
Setup: Encountered missing dependencies:
aeson >=0.9 && <0.12
```

If these bounds are removed, the package compiles and seems to work successfully. I know Hackage requires bounds but I'm not sure what the correct values should be.

**Comment by expipiplus1** [comment]
Fixed! Thanks!
