### ISSUE TITLE
It would be nice to be able to select a branch, what should the UI be?

### ISSUE THREAD

**Issue by expipiplus1** [expipiplus1/update-nix-fetchgit#24]
```nix
pkgs.fetchFromGitHub {
  owner = "..";
  repo = "..";
  rev = ".."; # branch-name
  sha256 = "..";
};
```

I think the above would be ideal. Probably wouldn't be *too* hard to extract that too.

**Comment by leotaku** [comment]
I agree that this feature would be very useful and also like the proposed syntax. However, from a quick glance at the HNix documentation, it seems like accessing the contents of a comment would not be trivially possible as they are discarded by the parser. Do you have any suggestions on how this should best be implemented?

**Comment by expipiplus1** [comment]
Well, we have the source location, so shouldn't be too hard to read the
input at that line (and preceding one) and look for an appropriate comment.

**Comment by expipiplus1** [comment]
I think there was some talk in a hnix issue about preserving comments in
annotations though. Don't think it was implemented, mind

**Comment by expipiplus1** [comment]
Something nasty which would be visible with hnix would be something like:

`rev = (pin: pin) "revision";` I think everyone will agree that's quite horrible

**Comment by expipiplus1** [comment]
Actually, there are quite a few ways of sneaking this in:

- `assert (true || "pin"); "hash"`
- `let _pin = true; in "hash`  (Not too bad)

**Comment by expipiplus1** [comment]
Have basically got the comment option working, comment has to be a single line comment on the same line as the expression. https://github.com/expipiplus1/update-nix-fetchgit/blob/2e9df344c40e289920e94c82dbce2d87ae54ecc5/src/Nix/Comments.hs
