### ISSUE TITLE
Be able to select tags for repos

### ISSUE THREAD

**Issue by expipiplus1** [expipiplus1/update-nix-fetchgit#26]
Something like

`update-nix-fetchgit --release user/repo@release-tag`

or without the tag to update to the latest release

**Comment by sorki** [comment]
I think this is already possible with `--rev` like

```
update-nix-fetchgit nix/nix-linter.nix --rev refs/tags/v0.2.0.0
```

when `--rev` is omitted it's basically just `--rev refs/heads/master`.

**Comment by expipiplus1** [comment]
oh, right! Thanks.
