### ISSUE TITLE
Build broken by hnix 0.13

### ISSUE THREAD

**Issue by sternenseemann** [expipiplus1/update-nix-fetchgit#62]
The type of `Result` changed in 0.13 to be an alias to `Either`. [Build log](https://hydra.nixos.org/build/143032797/nixlog/1).

**Comment by expipiplus1** [comment]
Thanks! Once hnix 0.13 is the default in `nixpkgs-unstable` then I'll take a look.

If you'd like this fixed before then then please feel free to open a PR with some CPP to support both versions :D

**Comment by Anton-Latukha** [comment]
We, this weird switchback I did, since `Either` is idiomatic, people read Right - understand "Successful computation", additional type there added nothing, only was harder understand semantically.

**Comment by expipiplus1** [comment]
Yeah, makes sense :)
